### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by e-bug** [eyalbetzalel/fcd#1]
Hi!

Thank you for open-sourcing your implementation :)
Could you please add a LICENSE file to the repository?
My institution requires it for me to use it.

Thanks!
Emanuele

**Comment by eyalbetzalel** [comment]
Done :)

If you use this code, please consider citing the [original article ](https://arxiv.org/abs/2206.10935)

**Comment by e-bug** [comment]
Thank you!
